# Generated by Django 5.1.4 on 2025-01-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_posts_filename_posts_original_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="original_filename",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="original_filename"
            ),
        ),
    ]
